---
title: "Time Series Data"
output: html_document
date: 'April 10, 2022'
---

The goal of this portfolio is to make sure that I can work with time series data when I have two variables from different data sets where the times do not match up perfectly. 
Here, I have data on suicide rates from 1999-2019. I have data from a separate source on social media usage over time, covering 2015-2021. 
Data on average number of minutes of U.S. social media usage by year comes from emarketer.com:
https://www.emarketer.com/content/average-social-media-time-spent
Data on suicide US rates comes from the official US government National Institute of Mental Health website:
https://www.nimh.nih.gov/health/statistics/suicide#part_2557

Let's see how we can isolate out only the years for which we have data on both variables, which would be the years 2015-2019.

1) First, installing packages / libraries. 
After creating my final visualization, then attempting to knit the file, R gave me an error message on line 20, so I removed this command from the knitted version:

``{r Packages}
install.packages('tidyr')
install.packages('readr')
```

```{r Library} 
library(ggplot2)
library(tidyr)
```

``{r DataCSV} 
library(readr)
TimeSeries <- read_csv("~/Documents/GitHub/Portfolio5-TimeSeries/TimeSeries.csv")
View(TimeSeries)
```

2) To isolate the specific years 2015-2019, we can use the following code. This code creates a separate df named "DateRange" containing the specific years we are interested in. 
The "write" command will save our df named "DateRange" as a csv. That way, we'll have a separate file containing our date range which we can share with others.

``{r DateRange}
DateRange <-TimeSeries [TimeSeries$Time >= "2015" & TimeSeries$Time <= "2019", ]
write.csv(DateRange, "~/Documents/GitHub/Portfolio5-TimeSeries/CsvfromDf.csv")
```

``{r Test1}
ggplot(DateRange, aes(Time)) +
  geom_line(aes(y = Value_SMM, color = "SMM")) + 
  geom_line(aes(y = Value_SR, color = "SR"))
```

Finally, to switch the color of these lines so that SR is red, we can manually change the colors assigned to each variable. Let's also add a legend.

``{r Test2} 
colors <- c("SMM" = "blue", "SR" = "red")
ggplot(DateRange, aes(x=Time)) +
  geom_line(aes(y = Value_SMM, color = "SMM"), size = 1.5) +
  geom_line(aes(y = Value_SR, color="SR"), size = 1.5) +
labs(                                
   x = "Year",
   y = "SR & SMM",
   color = "Legend"
 ) +
scale_color_manual(values = colors) 
```




